"""Filler tokens (Pfau, Merrill & Bowman 2024, arXiv:2404.15758): `compute_steps`
content-free tokens (e.g. repeated ".") between the question and the answer instead
of a genuine step-by-step rationale. Tests whether hidden computation happens across
those extra forward passes even though the tokens carry no task information.

Owner's notes go here. `compute_steps` = number of filler tokens; `compute_steps=0` is
the no-filler control -- always log it alongside any nonzero sweep point.

Gotchas for whoever implements it on GPT-2:
- GPT-2's BPE merges runs of "." into single tokens ("..." is one token), so a string
  of N dots does *not* tokenize to N filler tokens. Splice the filler token id N times
  into `input_ids` directly, and do it the same way at train and eval time.
- Pfau et al. found filler tokens only help with dense/parallel supervision on
  synthetic tasks; a null result on GSM8K-Aug is plausible and still a result.
- Prompt ends on `"Answer:"` (no trailing space) -- GPT-2's BPE encodes a leading
  space as part of the next token, so a template ending in a bare space shifts the
  first generated token's distribution (see explicit_cot.py's gotcha).

`compute_steps` here = number of filler tokens forced between the question and the
answer, at both train and eval time (not freely generated by the model -- forcing it
keeps `compute_steps` an exact, controlled independent variable for the sweep).
`compute_steps=0` is the no-filler control: prompt goes straight to the answer.

**Original (non-faithful) default:** training loss is masked over the prompt + filler
span; only the answer span (and EOS) is trained on.

**Paper-faithful mode** (`build_example_ids(..., mask_filler_loss=False)`, driven by
`scripts/train_filler_tokens.py --faithful`): checked against the paper's own released
training code (github.com/JacobPfau/fillerTokens), not just its prose, this default
deviates from their actual methodology in two ways that plausibly matter:
1. They train on a **uniform 50/50 mixture of chain-of-thought and filler-token
   sequences** in the same run (`cot_rate=0.5` in their data generator) -- not
   filler-only. Per their abstract, "learning to use filler tokens proves difficult
   and requires specific training"; this mixture is plausibly that training.
2. Their reference training mode (`mask='P'` in `tensorize_labels_worker`) does
   **not** mask loss over the filler span -- the model is trained to predict the
   filler tokens too, not just the final answer.
Both are cheap to match: mix in CoT-formatted examples (see `explicit_cot.py`,
`train_filler_tokens.py`'s `--faithful` builds the 50/50 mix) and pass
`mask_filler_loss=False` for the filler-formatted half. Eval is unaffected either way
-- the paper also evaluates on filler-only sequences ("Test on filler-token sequences
only"), which is what `build_eval_prompt_ids` already does.

**Why a null result here is expected, not just plausible:** the reference repo's
`src/match3.py` has both parallel (`dot_filler_parallel`) and serial/instance-adaptive
(`dot_filler_serial`, `serial_cot`) task variants, and the paper's own reported result
is that filler tokens **fail on the serial variant -- stay at baseline**, same as no
intermediate tokens. Their stated mechanism: serial/instance-adaptive computation
needs an actual intermediate result cached and carried forward token-to-token, and
filler tokens are content-free, so there's no channel for that. GSM8K-Aug arithmetic
chains are exactly this shape (each step needs the previous step's specific numeric
result), so a null result here is a replication of an effect the paper already
demonstrated on its own synthetic serial task, not a new finding -- the interesting
part is that it holds in a new domain (natural language) and model class (pretrained
GPT-2 vs. their from-scratch ~30M-param model), not that it holds at all. See
`HANDOFF.md`'s "Paper-faithful methodology audit" section (as of 2026-09-18; fold into
`PROPOSAL.md`/write-up before that file is deleted) for the full citation trail and
the structural differences (task class, model, scale, filler-budget-vs-difficulty
coupling) that this reproduction does *not* control for.

`scripts/train_filler_tokens.py` is the actual training/eval loop that uses these.
"""
from __future__ import annotations

from typing import Any

name = "filler_tokens"

PROMPT_TEMPLATE = "Question: {question}\nAnswer:"
ANSWER_TEMPLATE = " #### {answer}"


def _filler_token_id(tokenizer: Any, filler_token: str) -> int:
    ids = tokenizer(filler_token, add_special_tokens=False)["input_ids"]
    if len(ids) != 1:
        raise ValueError(f"filler_token {filler_token!r} is not a single token: {ids}")
    return ids[0]


def build_example_ids(
    tokenizer: Any,
    question: str,
    answer: str,
    compute_steps: int,
    filler_token: str = ".",
    mask_filler_loss: bool = True,
) -> tuple[list[int], list[int]]:
    """`(input_ids, labels)` for one training example: prompt + `compute_steps` forced
    filler tokens + answer + EOS. By default `labels` masks (`-100`) everything but the
    answer span. Pass `mask_filler_loss=False` to also train on predicting the filler
    span itself, matching the paper's own reference training code -- see the module
    docstring's "Paper-faithful mode" section."""
    prompt_ids = tokenizer(PROMPT_TEMPLATE.format(question=question), add_special_tokens=False)["input_ids"]
    filler_id = _filler_token_id(tokenizer, filler_token)
    answer_ids = tokenizer(ANSWER_TEMPLATE.format(answer=answer), add_special_tokens=False)["input_ids"]
    eos = tokenizer.eos_token_id
    input_ids = prompt_ids + [filler_id] * compute_steps + answer_ids + [eos]
    filler_labels = ([filler_id] if not mask_filler_loss else [-100]) * compute_steps
    labels = [-100] * len(prompt_ids) + filler_labels + answer_ids + [eos]
    return input_ids, labels


def build_eval_prompt_ids(tokenizer: Any, question: str, compute_steps: int, filler_token: str = ".") -> list[int]:
    """Prompt + forced filler, ready to hand to `model.generate` for the answer span."""
    prompt_ids = tokenizer(PROMPT_TEMPLATE.format(question=question), add_special_tokens=False)["input_ids"]
    filler_id = _filler_token_id(tokenizer, filler_token)
    return prompt_ids + [filler_id] * compute_steps
