"""Render results/README.md and EXPERIMENTS.md from results/<run_id>/{manifest.json,notes.md}.
Both files are generated -- never hand-edit; run `uv run python scripts/rebuild_index.py`.
"""
from __future__ import annotations

from pathlib import Path

from latentreasoning.runlog.manifest import REPO_ROOT, RESULTS_DIR, index_row, load_all_runs

GENERATED_NOTE = "<!-- GENERATED by scripts/rebuild_index.py from results/*/ -- do not hand-edit -->"

README_HEADER = f"""{GENERATED_NOTE}
# Results index

One row per logged run; click through for `manifest.json` (numbers) and `notes.md`
(narrative). Only compare accuracy across rows when `compute_steps`, split, n, dataset
seed, and run seed all match. Convention: `.claude/skills/record-run/SKILL.md`.

| run_id | mechanism | backbone | dataset | compute_steps | accuracy | seed | stage | author |
|---|---|---|---|---|---|---|---|---|
"""

EXPERIMENTS_HEADER = f"""{GENERATED_NOTE}
# Experiment Log

Concatenation of every `results/<run_id>/notes.md`, oldest first. To add or amend an
entry, edit that run's `notes.md` (append a correction rather than rewriting history) and
rerun `scripts/rebuild_index.py`.

---
"""


def render_results_readme(results_dir: Path = RESULTS_DIR) -> str:
    return README_HEADER + "".join(index_row(r) + "\n" for r in load_all_runs(results_dir))


def render_experiments_log(results_dir: Path = RESULTS_DIR) -> str:
    parts = []
    for r in load_all_runs(results_dir):
        notes = Path(results_dir) / r["run_id"] / "notes.md"
        body = notes.read_text().strip() if notes.exists() else f"## {r['run_id']}\n\n_(no notes.md)_"
        parts.append(body + "\n")
    return EXPERIMENTS_HEADER + "\n---\n\n".join(parts)


def rebuild(results_dir: Path = RESULTS_DIR, repo_root: Path = REPO_ROOT) -> None:
    (results_dir / "README.md").write_text(render_results_readme(results_dir))
    (repo_root / "EXPERIMENTS.md").write_text(render_experiments_log(results_dir))
